### ISSUE TITLE
Upgrade to latest Ganache. Why: older Ganache has a bug which delays chain update on tx, which breaks unit tests

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/barge#339]
### Background

(This was observed while doing dev on ocean.py, but it's a barge related issue)

Symptom: I'm running ocean.py tests locally. I run a test, and it fails. If I then put in a time.sleep(10) after a tx, and re-run the test, it passes. (Example: ocean_lib/models/tests/test_exchange_fees.py)

In short: it seems like there's a delay to blockchain txs going through.

I have encountered this randomly in the past. Though it seems to be worse now, I'm not sure why.

Maria and Calina have seen this too.

It makes debugging super-problematic.

It only happens locally, not on remote CI.

Examples of current failures I'm dealing with. In [this PR](https://github.com/oceanprotocol/ocean.py/pull/1154), some tests that fail:
- `ocean_lib/models/test/test_data_nft.py::test_success_update_metadata`. It fails on assert metadata_info[3], the most basic thing
- `ocean_lib/models/test/test_exchange_swap_fees.py`. See  `time.sleep(10)` that are workarounds so that it tries to pass. But that sometimes isn't enough either, so I have pytest.mark.skip()'d the tests.

----
Calina: I also think it might be a ganache issue

Like described here, where a new version fixed some caching issues https://github.com/trufflesuite/ganache/issues/587
- it even changed its name from ganache-cli months ago https://hub.docker.com/r/trufflesuite/ganache-cli/
- and the old version seems un-maintained

And we’re apparently using an older ganache

### TODOs

- [ ] In barge, update to latest ganache. Ship it
- [ ] Ensure if there was any breakage in ocean.py, it gets fixed
- [ ] Put a comment in [ocean.py#1176](https://github.com/oceanprotocol/ocean.py/issues/1176) that _this_ issue is done, which will ping respective parties that work on it can proceed

**Comment by md00ux** [comment]
please test using `feature/ganache_upgrade` branch from barge.

**Comment by AnaLoznianu** [comment]
We need to test this on the ocean.py, aquarius, subgraph, ocean.js

**Comment by trentmc** [comment]
Merged. Closing.
