### ISSUE TITLE
Goal: predictoor branch merged into main

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/barge#391]
### Background

For several months, barge has had a "predictoor" branch. If we're doing anything with predictoor, we need to switch to this branch. But that can lead to issues. Eg [#390](https://github.com/oceanprotocol/barge/issues/390) where Barge took 5-10 retries to get going; and getting in sync with main got it back to 1 try.

Benefits, more generally: Minimizes issues like the above happening again. And better UX for predictoor users. And better dev UX for barge.

One more near-term benefit: we want to merge pdr-backend YAML-CLI work ASAP, and merging this branch will help that work. Details in [barge#393](https://github.com/oceanprotocol/barge/issues/393).

### On switches

Alex: we need some switches

Trent:  do remember that there already are several predictoor-specific switches:

- deploy predictoor smart contracts yes/no? Default = no
- for each bot: run yes/no? Default = no
- maybe more?

Alex: they are related to ganache.  I need to make sure that --predictoor switch starts ganache with block time, and all other switches are not doing this.  cause we may have some hardcoded values :slightly_smiling_face:

### TODOs

- [x] [Alex] Core thing: in barge repo, merge `predictoor` branch into "main" branch. How: commit https://github.com/oceanprotocol/barge/commit/61287b3dccdd46093f277b068019053eede74310
  - [x] Ensure issues wrt switches are resolved. And any other issues
- [x] [Trent] In predictoor repo, for its (a) github actions and (b) READMEs on running barge: update to _not_ use `predictoor` branch
  - [x] In predictoor `main` branch. How: [pdr-backend PR#420](https://github.com/oceanprotocol/pdr-backend/pull/420), commit https://github.com/oceanprotocol/pdr-backend/commit/bcaf4f3d3788aa6210aaa6b39f980ad101ee4259
  - [x] In predictoor `yaml-cli2` branch. How: commit https://github.com/oceanprotocol/pdr-backend/commit/995df8b0271452180abd9f50a6445d5a22206bba
- [x] In barge repo: delete `predictoor` branch
